module.exports = {
  name: '標我',
  description: 'Just tag',
  execute(msg, args, prefix, command, author, master) {
    const messages = [
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `${msg.author}`,
      `可憐你的\n${msg.author}`,
      '偏不要',
      '想得美',
      '我拒絕',
      '想太多',
    ];
    const randomMessage = messages[Math.floor(Math.random() * messages.length)];
    msg.channel.send(randomMessage);
  },
};
